### ISSUE TITLE
File not found error when executing action

### ISSUE THREAD

**Issue by swyngaard** [vortegon/github-action-ansible-tower#4]
I get the following error log when running the action
```

Run vortegon/github-action-ansible-tower@v1.0.5
  with:
    ansible-tower-user: ***
    ansible-tower-pass: ***
    ansible-tower-url: ***
    template-id: 36
Error: File not found: '/home/runner/work/_actions/vortegon/github-action-ansible-tower/v1.0.5/dist/main.js'
```
This is the workflow YAML:
```yaml
name: Deploy via Ansible AWX
on:
  push:
    branches:
      - main
      - feature/trigger_deploy_on_merge

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy via Ansible AWX
      uses: vortegon/github-action-ansible-tower@v1.0.5
      with:
        ansible-tower-user: ${{ secrets.ansibleUser }}
        ansible-tower-pass: ${{ secrets.ansiblePass }}
        ansible-tower-url: ${{ secrets.ansibleUrl }}
        template-id: "36"

```
Any ideas about how to resolve this? It seems like the node.js distribution files are missing.
